### ISSUE TITLE
[FEATURE] CI/CD flow for pull request

### ISSUE THREAD

**Issue by ZebraRoy** [The-Pocket/PocketFlow-Typescript#16]
## Problem Statement

Current project is missing CI/CD flow. It may cause some breaking code enter the project

## Proposed Solution

Add github ci/cd pipeline to run the test before merge

## Example Implementation

```yaml
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

```
